### ISSUE TITLE
console堆栈信息优化

### ISSUE THREAD

**Issue by nonameShijian** [Nice-PLQ/devtools-remote-debugger#33]
在使用v8引擎的浏览器网页，或许可以使用Error.captureStackTrace来优化堆栈信息忽略掉控制台本身调用的堆栈

例如:
```
at eval (eval at _proto.evaluate (https://localhost/sdk.js:2:12735), <anonymous>:4:1)
at eval (<anonymous>)
at _proto.evaluate (https://localhost/sdk.js:2:12735)
at t.execute (https://localhost/sdk.js:2:77160)
at https://localhost/sdk.js:2:80039
at e._callEventListener (https://localhost/sdk.js:2:24309)
at https://localhost/sdk.js:2:17992
at Array.forEach (<anonymous>)
at WebSocket._handleMessage (https://localhost/sdk.js:2:17962)
```

**Comment by Nice-PLQ** [comment]
确实可以做下过滤
